app_product:
    resource: "@AppBundle/Resources/config/routing/product.yml"
    prefix:   /product


homepage:
    path:     /
    defaults: { _controller: AppBundle:App:index }

user_delete:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:User:delete }
    requirements:
        id: \d+

user_index:
    path:     /user
    defaults: { _controller: AppBundle:User:index }
